### ISSUE TITLE
Secret mariadb not found

### ISSUE THREAD

**Issue by mgerum** [digitalist-se/directus-helm-chart#16]
Hello and thanks for your contribution,

I'm having problems with the simple chart helm setup.

`Error: secret "my-release-name-directus-mariadb" not found` into the pod directus.

Tried: 
`helm install my-release-name --set key=myrandomkey --set secret=myrandomsecret directus/directus`
`helm install my-release-name --set key=myrandomkey --set secret=myrandomsecret directus/directus --set mariadb.auth.rootPassword=secret`

Thank you.

**Comment by mikkeschiren** [comment]
Interesting. Does the secret exist for mariadb?

**Comment by mikkeschiren** [comment]
Or maybe you are installing without the included mariadb?

**Comment by mgerum** [comment]
No I use your standard implementation with mariadb,

Here is the list of my secrets:

my-release-name-directus-secrets        Opaque               2      19s
my-release-name-mariadb                 Opaque               2      19s
my-release-name-redis                   Opaque               1      19s

**Comment by mikkeschiren** [comment]
Hm... So the issues should be from this:
https://github.com/digitalist-se/directus-helm-chart/blob/main/charts/directus/templates/deployment.yaml#L227C1-L231C40

I investigate.

**Comment by mikkeschiren** [comment]
This should be fixed by https://github.com/digitalist-se/directus-helm-chart/pull/25 - so if you could try to install again with the latest release?

```
helm repo update
helm install my-release-name --set key=myrandomkey --set secret=myrandomsecret directus/directus
```

**Comment by mgerum** [comment]
Yes it's okay now. Thank you for your reactivity.

**Comment by mikkeschiren** [comment]
Great! And thanks for the report.
