### ISSUE TITLE
backend is unused in Ingress

### ISSUE THREAD

**Issue by tonnyavery** [digitalist-se/directus-helm-chart#56]
https://github.com/digitalist-se/directus-helm-chart/blob/fc79e64d7560a8989181fd07de9bf30bcbe407f9/charts/directus/values.yaml#L101

Looking at the code, `backend` seems to always be configured to the service, not to the values coming from values.yaml. Probably just values.yaml needs updating

**Comment by mikkeschiren** [comment]
Thanks for noticing! This should be fixed now. Please reopen if I am wrong :)
