### ISSUE TITLE
host should be optional for ingress resource

### ISSUE THREAD

**Issue by tonnyavery** [digitalist-se/directus-helm-chart#57]
https://github.com/digitalist-se/directus-helm-chart/blob/fc79e64d7560a8989181fd07de9bf30bcbe407f9/charts/directus/templates/ingress.yaml#L34

Building up directus setup step by step, I don't have a domain yet to set as a valid host.
Making `host` optional will allow to test directus setup on ip address

**Comment by tonnyavery** [comment]
Should be possible to have `host: ""` to skip it, not sure?

**Comment by tonnyavery** [comment]
this results in issues as `public_url` is enforced to either be manually configured or set to ingress host

**Comment by mikkeschiren** [comment]
This should be solved, so closing, reopen if I misunderstood the issue :)
